name = "hpg"
uuid = "b20249b2-010b-4d3f-9d32-f15d2ff14e30"
authors = ["Alphonsus Adu-Bredu"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
